[build]
  publish = "."
  command = "echo 'Static site'"

[[redirects]]
  from = "/api/*"
  to = "https://cinerate.fly.dev/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
